const names= require('./names')
const sayHi=require('./utils')
const {items,singlePerson} =require('./alternate_flavous')
require('./calculate')
console.log(items)
console.log(singlePerson)
sayHi(names.john)
sayHi(names.peter)
sayHi(names.gwen)
